//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class acceso_sistema
    {
        public int cod_acceso { get; set; }
        public System.DateTime fecha_acceso { get; set; }
        public string dir_acceso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string cod_user { get; set; }
        public string estado_acceso { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
