//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int codasistencia { get; set; }
        public string cod_personal { get; set; }
        public System.DateTime fechaasistencia { get; set; }
        public System.TimeSpan horaasistemcia { get; set; }
        public string estado { get; set; }
    
        public virtual personal personal { get; set; }
    }
}
