//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta_deta
    {
        public string cod_pago { get; set; }
        public string cod_menu { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
        public decimal prec_unit { get; set; }
    
        public virtual boleta_cabe boleta_cabe { get; set; }
        public virtual menu menu { get; set; }
    }
}
