//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_plato
    {
        public cat_plato()
        {
            this.menu = new HashSet<menu>();
        }
    
        public int cod_cat_plato { get; set; }
        public string nomcat { get; set; }
        public string descrip_cat { get; set; }
    
        public virtual ICollection<menu> menu { get; set; }
    }
}
