//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.boleta_cabe = new HashSet<boleta_cabe>();
            this.ped_delivery_cabe = new HashSet<ped_delivery_cabe>();
            this.puntos = new HashSet<puntos>();
            this.reservacion = new HashSet<reservacion>();
            this.factura_cabe = new HashSet<factura_cabe>();
        }
    
        public string cod_cli { get; set; }
        public string nomcliente { get; set; }
        public string apecliente { get; set; }
        public string imagen { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string cod_distrito { get; set; }
        public string DNI_RUC { get; set; }
        public string observacion { get; set; }
        public string tipo_cliente { get; set; }
        public int cod_usu_cli { get; set; }
    
        public virtual ICollection<boleta_cabe> boleta_cabe { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual usuarioCliente usuarioCliente { get; set; }
        public virtual ICollection<ped_delivery_cabe> ped_delivery_cabe { get; set; }
        public virtual ICollection<puntos> puntos { get; set; }
        public virtual ICollection<reservacion> reservacion { get; set; }
        public virtual ICollection<factura_cabe> factura_cabe { get; set; }
    }
}
