//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_entrada_insumo
    {
        public int cod_det_entrada { get; set; }
        public Nullable<int> cod_entrada { get; set; }
        public string codisumos { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> sub_total { get; set; }
    
        public virtual Entrada_insumo Entrada_insumo { get; set; }
        public virtual insumo insumo { get; set; }
    }
}
