//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_puntos
    {
        public int cod_detalle_puntos { get; set; }
        public Nullable<int> cantidad_insercion { get; set; }
        public Nullable<System.DateTime> fecha_insercion { get; set; }
        public Nullable<System.TimeSpan> hora_insercion { get; set; }
        public Nullable<int> cod_punto { get; set; }
        public Nullable<int> cod_venta { get; set; }
    
        public virtual puntos puntos { get; set; }
        public virtual venta venta { get; set; }
    }
}
