//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada_insumo
    {
        public Entrada_insumo()
        {
            this.detalle_entrada_insumo = new HashSet<detalle_entrada_insumo>();
        }
    
        public int cod_entrada { get; set; }
        public string cod_prove { get; set; }
        public string cod_personal { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public string num_factura { get; set; }
        public Nullable<decimal> total_compra { get; set; }
    
        public virtual ICollection<detalle_entrada_insumo> detalle_entrada_insumo { get; set; }
        public virtual personal personal { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
