//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_cabe
    {
        public factura_cabe()
        {
            this.factura_deta = new HashSet<factura_deta>();
        }
    
        public string cod_factura { get; set; }
        public string cod_cli { get; set; }
        public string RUC { get; set; }
        public string cod_tip_comprobante { get; set; }
        public string cod_personal { get; set; }
        public System.DateTime fecha_emicion { get; set; }
        public Nullable<decimal> igv { get; set; }
        public int cod_cupon { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> total { get; set; }
        public int cod_venta { get; set; }
        public string estado_pago { get; set; }
        public Nullable<decimal> sub_total { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual detalle_promocion detalle_promocion { get; set; }
        public virtual tipo_comprobante tipo_comprobante { get; set; }
        public virtual venta venta { get; set; }
        public virtual personal personal { get; set; }
        public virtual ICollection<factura_deta> factura_deta { get; set; }
    }
}
