//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.factura_deta = new HashSet<factura_deta>();
            this.ped_delivery_deta = new HashSet<ped_delivery_deta>();
            this.boleta_deta = new HashSet<boleta_deta>();
            this.orden_detalle = new HashSet<orden_detalle>();
        }
    
        public string cod_menu { get; set; }
        public int cod_cat_plato { get; set; }
        public string nomplato { get; set; }
        public decimal precio { get; set; }
        public string estado_plato { get; set; }
        public string imagen { get; set; }
        public System.DateTime fecha { get; set; }
        public int cantidad { get; set; }
        public string descrip_men { get; set; }
    
        public virtual cat_plato cat_plato { get; set; }
        public virtual ICollection<factura_deta> factura_deta { get; set; }
        public virtual ICollection<ped_delivery_deta> ped_delivery_deta { get; set; }
        public virtual ICollection<boleta_deta> boleta_deta { get; set; }
        public virtual ICollection<orden_detalle> orden_detalle { get; set; }
    }
}
