//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_cabe
    {
        public orden_cabe()
        {
            this.orden_detalle = new HashSet<orden_detalle>();
        }
    
        public int cod_orden { get; set; }
        public string cod_personal { get; set; }
        public string estado_orden { get; set; }
        public int cod_mesa { get; set; }
        public System.DateTime fecha_orden { get; set; }
    
        public virtual mesa mesa { get; set; }
        public virtual personal personal { get; set; }
        public virtual ICollection<orden_detalle> orden_detalle { get; set; }
    }
}
