//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_detalle
    {
        public int cantidad { get; set; }
        public string cod_menu { get; set; }
        public int cod_orden { get; set; }
        public decimal precio { get; set; }
        public decimal subtotal_orden { get; set; }
        public string estado_orden_plato { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual orden_cabe orden_cabe { get; set; }
    }
}
