//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_Cabe
    {
        public pedido_Cabe()
        {
            this.pedido_deta = new HashSet<pedido_deta>();
        }
    
        public string cod_ped_cabe { get; set; }
        public System.DateTime fechapedido { get; set; }
        public string cod_prove { get; set; }
        public string cod_personal { get; set; }
        public string estado_pedido { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        public virtual ICollection<pedido_deta> pedido_deta { get; set; }
        public virtual personal personal { get; set; }
    }
}
