//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_cargo
    {
        public per_cargo()
        {
            this.personal = new HashSet<personal>();
        }
    
        public string cod_per_cargo { get; set; }
        public string nomcargo { get; set; }
        public string desc_cargo { get; set; }
    
        public virtual ICollection<personal> personal { get; set; }
    }
}
