//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public personal()
        {
            this.asistencia = new HashSet<asistencia>();
            this.boleta_cabe = new HashSet<boleta_cabe>();
            this.Entrada_insumo = new HashSet<Entrada_insumo>();
            this.factura_cabe = new HashSet<factura_cabe>();
            this.orden_cabe = new HashSet<orden_cabe>();
            this.ped_delivery_cabe = new HashSet<ped_delivery_cabe>();
            this.pedido_Cabe = new HashSet<pedido_Cabe>();
            this.salida_insumo = new HashSet<salida_insumo>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public string cod_personal { get; set; }
        public string nompersonal { get; set; }
        public string apepersonal { get; set; }
        public string dni { get; set; }
        public byte[] foto { get; set; }
        public string direccion { get; set; }
        public string cod_distrito { get; set; }
        public string telefono { get; set; }
        public string genero { get; set; }
        public System.DateTime fecnac { get; set; }
        public string cod_per_cargo { get; set; }
        public System.DateTime fechacontratacion { get; set; }
        public System.DateTime fechafincontrato { get; set; }
        public string turno { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<asistencia> asistencia { get; set; }
        public virtual ICollection<boleta_cabe> boleta_cabe { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual ICollection<Entrada_insumo> Entrada_insumo { get; set; }
        public virtual ICollection<factura_cabe> factura_cabe { get; set; }
        public virtual ICollection<orden_cabe> orden_cabe { get; set; }
        public virtual ICollection<ped_delivery_cabe> ped_delivery_cabe { get; set; }
        public virtual ICollection<pedido_Cabe> pedido_Cabe { get; set; }
        public virtual per_cargo per_cargo { get; set; }
        public virtual ICollection<salida_insumo> salida_insumo { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
