//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocion
    {
        public promocion()
        {
            this.detalle_promocion = new HashSet<detalle_promocion>();
        }
    
        public int cod_promo { get; set; }
        public string nombre_promocion { get; set; }
        public string descripcion_promo { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> stock_promo { get; set; }
        public Nullable<int> puntos_necesarios { get; set; }
        public Nullable<decimal> valor_descuento { get; set; }
        public Nullable<bool> impreso { get; set; }
        public Nullable<int> cod_tipo_descuento { get; set; }
    
        public virtual ICollection<detalle_promocion> detalle_promocion { get; set; }
        public virtual tipo_descuento tipo_descuento { get; set; }
    }
}
