//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntos
    {
        public puntos()
        {
            this.detalle_puntos = new HashSet<detalle_puntos>();
        }
    
        public int cod_punto { get; set; }
        public Nullable<int> total_puntos { get; set; }
        public Nullable<System.DateTime> ultima_insercion { get; set; }
        public string cod_cli { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<detalle_puntos> detalle_puntos { get; set; }
    }
}
