//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida_insumo
    {
        public salida_insumo()
        {
            this.detalle_salida_insumo = new HashSet<detalle_salida_insumo>();
        }
    
        public int cod_salida { get; set; }
        public string cod_personal { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
    
        public virtual ICollection<detalle_salida_insumo> detalle_salida_insumo { get; set; }
        public virtual personal personal { get; set; }
    }
}
