//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_comprobante
    {
        public tipo_comprobante()
        {
            this.boleta_cabe = new HashSet<boleta_cabe>();
            this.factura_cabe = new HashSet<factura_cabe>();
        }
    
        public string cod_tip_comprobante { get; set; }
        public string nomcomprobante { get; set; }
        public string desc_comprobante { get; set; }
    
        public virtual ICollection<boleta_cabe> boleta_cabe { get; set; }
        public virtual ICollection<factura_cabe> factura_cabe { get; set; }
    }
}
