//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidad_medida
    {
        public unidad_medida()
        {
            this.insumo = new HashSet<insumo>();
        }
    
        public int cod_unidad_medida { get; set; }
        public string nombre_unidad_medida { get; set; }
        public string descripcion_unidad_medida { get; set; }
    
        public virtual ICollection<insumo> insumo { get; set; }
    }
}
