//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.acceso_sistema = new HashSet<acceso_sistema>();
        }
    
        public string cod_user { get; set; }
        public string contrasena { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string cod_personal { get; set; }
        public string estado_user { get; set; }
    
        public virtual ICollection<acceso_sistema> acceso_sistema { get; set; }
        public virtual personal personal { get; set; }
    }
}
