//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.boleta_cabe = new HashSet<boleta_cabe>();
            this.detalle_puntos = new HashSet<detalle_puntos>();
            this.factura_cabe = new HashSet<factura_cabe>();
        }
    
        public int cod_venta { get; set; }
        public Nullable<decimal> total_venta { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
    
        public virtual ICollection<boleta_cabe> boleta_cabe { get; set; }
        public virtual ICollection<detalle_puntos> detalle_puntos { get; set; }
        public virtual ICollection<factura_cabe> factura_cabe { get; set; }
    }
}
