//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BDLas_DeliciasEntities : DbContext
    {
        public BDLas_DeliciasEntities()
            : base("name=BDLas_DeliciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acceso_sistema> acceso_sistema { get; set; }
        public DbSet<asistencia> asistencia { get; set; }
        public DbSet<boleta_cabe> boleta_cabe { get; set; }
        public DbSet<cat_insumo> cat_insumo { get; set; }
        public DbSet<cat_plato> cat_plato { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<detalle_entrada_insumo> detalle_entrada_insumo { get; set; }
        public DbSet<detalle_promocion> detalle_promocion { get; set; }
        public DbSet<detalle_puntos> detalle_puntos { get; set; }
        public DbSet<detalle_salida_insumo> detalle_salida_insumo { get; set; }
        public DbSet<distrito> distrito { get; set; }
        public DbSet<Entrada_insumo> Entrada_insumo { get; set; }
        public DbSet<factura_cabe> factura_cabe { get; set; }
        public DbSet<insumo> insumo { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<mesa> mesa { get; set; }
        public DbSet<orden_cabe> orden_cabe { get; set; }
        public DbSet<ped_delivery_cabe> ped_delivery_cabe { get; set; }
        public DbSet<pedido_Cabe> pedido_Cabe { get; set; }
        public DbSet<per_cargo> per_cargo { get; set; }
        public DbSet<personal> personal { get; set; }
        public DbSet<promocion> promocion { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<puntos> puntos { get; set; }
        public DbSet<reservacion> reservacion { get; set; }
        public DbSet<salida_insumo> salida_insumo { get; set; }
        public DbSet<tipo_comprobante> tipo_comprobante { get; set; }
        public DbSet<tipo_descuento> tipo_descuento { get; set; }
        public DbSet<unidad_medida> unidad_medida { get; set; }
        public DbSet<usuarioCliente> usuarioCliente { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<venta> venta { get; set; }
        public DbSet<boleta_deta> boleta_deta { get; set; }
        public DbSet<factura_deta> factura_deta { get; set; }
        public DbSet<orden_detalle> orden_detalle { get; set; }
        public DbSet<ped_delivery_deta> ped_delivery_deta { get; set; }
        public DbSet<pedido_deta> pedido_deta { get; set; }
    
        public virtual int actualizar_cargo(string cod, string nombre, string descripcion)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_cargo", codParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int actualizar_cat_plato(Nullable<int> codigo, string nombre, string descrip)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_cat_plato", codigoParameter, nombreParameter, descripParameter);
        }
    
        public virtual int actualizar_cliente(string cod, string nombre, string apellido, string telefono, string direccion, string distrito, string dni, string observacion, string tipocliente)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var tipoclienteParameter = tipocliente != null ?
                new ObjectParameter("tipocliente", tipocliente) :
                new ObjectParameter("tipocliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_cliente", codParameter, nombreParameter, apellidoParameter, telefonoParameter, direccionParameter, distritoParameter, dniParameter, observacionParameter, tipoclienteParameter);
        }
    
        public virtual int Actualizar_insumo(string codinsu, string nominsu, Nullable<int> cod_unidad_medida, Nullable<decimal> peso, Nullable<int> codcat)
        {
            var codinsuParameter = codinsu != null ?
                new ObjectParameter("codinsu", codinsu) :
                new ObjectParameter("codinsu", typeof(string));
    
            var nominsuParameter = nominsu != null ?
                new ObjectParameter("nominsu", nominsu) :
                new ObjectParameter("nominsu", typeof(string));
    
            var cod_unidad_medidaParameter = cod_unidad_medida.HasValue ?
                new ObjectParameter("cod_unidad_medida", cod_unidad_medida) :
                new ObjectParameter("cod_unidad_medida", typeof(int));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(decimal));
    
            var codcatParameter = codcat.HasValue ?
                new ObjectParameter("codcat", codcat) :
                new ObjectParameter("codcat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_insumo", codinsuParameter, nominsuParameter, cod_unidad_medidaParameter, pesoParameter, codcatParameter);
        }
    
        public virtual int actualizar_personal(string codper, string codcargo, string nombre, string dni, string direccion, string telefono, string genero, string apellido, Nullable<System.DateTime> fechanacimiento, Nullable<System.DateTime> fechacontratacion, string coddistrito, string turno, string estado, Nullable<System.DateTime> fechafincontrato, byte[] foto)
        {
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            var codcargoParameter = codcargo != null ?
                new ObjectParameter("codcargo", codcargo) :
                new ObjectParameter("codcargo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var fechanacimientoParameter = fechanacimiento.HasValue ?
                new ObjectParameter("fechanacimiento", fechanacimiento) :
                new ObjectParameter("fechanacimiento", typeof(System.DateTime));
    
            var fechacontratacionParameter = fechacontratacion.HasValue ?
                new ObjectParameter("fechacontratacion", fechacontratacion) :
                new ObjectParameter("fechacontratacion", typeof(System.DateTime));
    
            var coddistritoParameter = coddistrito != null ?
                new ObjectParameter("coddistrito", coddistrito) :
                new ObjectParameter("coddistrito", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechafincontratoParameter = fechafincontrato.HasValue ?
                new ObjectParameter("fechafincontrato", fechafincontrato) :
                new ObjectParameter("fechafincontrato", typeof(System.DateTime));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_personal", codperParameter, codcargoParameter, nombreParameter, dniParameter, direccionParameter, telefonoParameter, generoParameter, apellidoParameter, fechanacimientoParameter, fechacontratacionParameter, coddistritoParameter, turnoParameter, estadoParameter, fechafincontratoParameter, fotoParameter);
        }
    
        public virtual int actualizar_plato(string codigo, Nullable<int> catplato, string nomplato, Nullable<decimal> precio, string estado, Nullable<System.DateTime> fecha, Nullable<int> cantidad, string descrip)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var catplatoParameter = catplato.HasValue ?
                new ObjectParameter("catplato", catplato) :
                new ObjectParameter("catplato", typeof(int));
    
            var nomplatoParameter = nomplato != null ?
                new ObjectParameter("nomplato", nomplato) :
                new ObjectParameter("nomplato", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_plato", codigoParameter, catplatoParameter, nomplatoParameter, precioParameter, estadoParameter, fechaParameter, cantidadParameter, descripParameter);
        }
    
        public virtual int actualizar_promocion(Nullable<int> cod_promo, string nombre_promocion, string descripcion_promocion, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin, Nullable<int> stock_promo, Nullable<int> puntos_necesarios, Nullable<decimal> valor_descuento, Nullable<bool> estado_promo, Nullable<int> cod_tipo_descuento)
        {
            var cod_promoParameter = cod_promo.HasValue ?
                new ObjectParameter("cod_promo", cod_promo) :
                new ObjectParameter("cod_promo", typeof(int));
    
            var nombre_promocionParameter = nombre_promocion != null ?
                new ObjectParameter("nombre_promocion", nombre_promocion) :
                new ObjectParameter("nombre_promocion", typeof(string));
    
            var descripcion_promocionParameter = descripcion_promocion != null ?
                new ObjectParameter("descripcion_promocion", descripcion_promocion) :
                new ObjectParameter("descripcion_promocion", typeof(string));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            var stock_promoParameter = stock_promo.HasValue ?
                new ObjectParameter("stock_promo", stock_promo) :
                new ObjectParameter("stock_promo", typeof(int));
    
            var puntos_necesariosParameter = puntos_necesarios.HasValue ?
                new ObjectParameter("puntos_necesarios", puntos_necesarios) :
                new ObjectParameter("puntos_necesarios", typeof(int));
    
            var valor_descuentoParameter = valor_descuento.HasValue ?
                new ObjectParameter("valor_descuento", valor_descuento) :
                new ObjectParameter("valor_descuento", typeof(decimal));
    
            var estado_promoParameter = estado_promo.HasValue ?
                new ObjectParameter("estado_promo", estado_promo) :
                new ObjectParameter("estado_promo", typeof(bool));
    
            var cod_tipo_descuentoParameter = cod_tipo_descuento.HasValue ?
                new ObjectParameter("cod_tipo_descuento", cod_tipo_descuento) :
                new ObjectParameter("cod_tipo_descuento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_promocion", cod_promoParameter, nombre_promocionParameter, descripcion_promocionParameter, fecha_inicioParameter, fecha_finParameter, stock_promoParameter, puntos_necesariosParameter, valor_descuentoParameter, estado_promoParameter, cod_tipo_descuentoParameter);
        }
    
        public virtual int Actualizar_proveedor(string codprov, string nomprov, string direc, string nomcont, string cargcont, string telfprov, string faxprov, string coddist, string ruc)
        {
            var codprovParameter = codprov != null ?
                new ObjectParameter("codprov", codprov) :
                new ObjectParameter("codprov", typeof(string));
    
            var nomprovParameter = nomprov != null ?
                new ObjectParameter("nomprov", nomprov) :
                new ObjectParameter("nomprov", typeof(string));
    
            var direcParameter = direc != null ?
                new ObjectParameter("direc", direc) :
                new ObjectParameter("direc", typeof(string));
    
            var nomcontParameter = nomcont != null ?
                new ObjectParameter("nomcont", nomcont) :
                new ObjectParameter("nomcont", typeof(string));
    
            var cargcontParameter = cargcont != null ?
                new ObjectParameter("cargcont", cargcont) :
                new ObjectParameter("cargcont", typeof(string));
    
            var telfprovParameter = telfprov != null ?
                new ObjectParameter("telfprov", telfprov) :
                new ObjectParameter("telfprov", typeof(string));
    
            var faxprovParameter = faxprov != null ?
                new ObjectParameter("faxprov", faxprov) :
                new ObjectParameter("faxprov", typeof(string));
    
            var coddistParameter = coddist != null ?
                new ObjectParameter("coddist", coddist) :
                new ObjectParameter("coddist", typeof(string));
    
            var rucParameter = ruc != null ?
                new ObjectParameter("ruc", ruc) :
                new ObjectParameter("ruc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_proveedor", codprovParameter, nomprovParameter, direcParameter, nomcontParameter, cargcontParameter, telfprovParameter, faxprovParameter, coddistParameter, rucParameter);
        }
    
        public virtual int actualizar_reserva(string cod, Nullable<System.DateTime> fechareservada, string cliente, string estado, Nullable<int> codmesa, Nullable<System.TimeSpan> hora)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var fechareservadaParameter = fechareservada.HasValue ?
                new ObjectParameter("fechareservada", fechareservada) :
                new ObjectParameter("fechareservada", typeof(System.DateTime));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var codmesaParameter = codmesa.HasValue ?
                new ObjectParameter("codmesa", codmesa) :
                new ObjectParameter("codmesa", typeof(int));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_reserva", codParameter, fechareservadaParameter, clienteParameter, estadoParameter, codmesaParameter, horaParameter);
        }
    
        public virtual int actualizar_sistema(Nullable<int> cod_acceso, Nullable<System.DateTime> fechasalida, string estado)
        {
            var cod_accesoParameter = cod_acceso.HasValue ?
                new ObjectParameter("cod_acceso", cod_acceso) :
                new ObjectParameter("cod_acceso", typeof(int));
    
            var fechasalidaParameter = fechasalida.HasValue ?
                new ObjectParameter("fechasalida", fechasalida) :
                new ObjectParameter("fechasalida", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_sistema", cod_accesoParameter, fechasalidaParameter, estadoParameter);
        }
    
        public virtual int actualizar_usuario(string dni, string contrasena, Nullable<System.DateTime> fechamodificacion, string estado)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var fechamodificacionParameter = fechamodificacion.HasValue ?
                new ObjectParameter("fechamodificacion", fechamodificacion) :
                new ObjectParameter("fechamodificacion", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_usuario", dniParameter, contrasenaParameter, fechamodificacionParameter, estadoParameter);
        }
    
        public virtual ObjectResult<buscar_asistenciaper_Result> buscar_asistenciaper(string codper, Nullable<System.DateTime> fecha)
        {
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_asistenciaper_Result>("buscar_asistenciaper", codperParameter, fechaParameter);
        }
    
        public virtual ObjectResult<buscar_cargo_Result> buscar_cargo(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cargo_Result>("buscar_cargo", codParameter);
        }
    
        public virtual ObjectResult<buscar_cat_plato_Result> buscar_cat_plato(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cat_plato_Result>("buscar_cat_plato", codigoParameter);
        }
    
        public virtual ObjectResult<buscar_cat_plato2_Result> buscar_cat_plato2(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cat_plato2_Result>("buscar_cat_plato2", nombreParameter);
        }
    
        public virtual ObjectResult<buscar_cliente_Result> buscar_cliente(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cliente_Result>("buscar_cliente", codParameter);
        }
    
        public virtual ObjectResult<buscar_cliente2_Result> buscar_cliente2(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cliente2_Result>("buscar_cliente2", dniParameter);
        }
    
        public virtual ObjectResult<buscar_cliente3_Result> buscar_cliente3(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cliente3_Result>("buscar_cliente3", codParameter);
        }
    
        public virtual ObjectResult<buscar_cupo_Result> buscar_cupo(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_cupo_Result>("buscar_cupo", codParameter);
        }
    
        public virtual ObjectResult<buscar_dely_fecha_Result> buscar_dely_fecha(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_dely_fecha_Result>("buscar_dely_fecha", fechaParameter);
        }
    
        public virtual ObjectResult<buscar_emple2_Result> buscar_emple2(string codper)
        {
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_emple2_Result>("buscar_emple2", codperParameter);
        }
    
        public virtual ObjectResult<buscar_emple3_Result> buscar_emple3(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_emple3_Result>("buscar_emple3", dniParameter);
        }
    
        public virtual ObjectResult<Buscar_insumo_Result> Buscar_insumo(string codinsu)
        {
            var codinsuParameter = codinsu != null ?
                new ObjectParameter("codinsu", codinsu) :
                new ObjectParameter("codinsu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Buscar_insumo_Result>("Buscar_insumo", codinsuParameter);
        }
    
        public virtual ObjectResult<Buscar_insumo2_Result> Buscar_insumo2(string nominsu)
        {
            var nominsuParameter = nominsu != null ?
                new ObjectParameter("nominsu", nominsu) :
                new ObjectParameter("nominsu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Buscar_insumo2_Result>("Buscar_insumo2", nominsuParameter);
        }
    
        public virtual ObjectResult<buscar_menu_Result> buscar_menu(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_menu_Result>("buscar_menu", codigoParameter);
        }
    
        public virtual ObjectResult<buscar_menu_2_Result> buscar_menu_2(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_menu_2_Result>("buscar_menu_2", nombreParameter);
        }
    
        public virtual ObjectResult<buscar_menu_3_Result> buscar_menu_3(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_menu_3_Result>("buscar_menu_3", codigoParameter);
        }
    
        public virtual ObjectResult<buscar_personal_Result> buscar_personal(string dni, string cargo)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("cargo", cargo) :
                new ObjectParameter("cargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_personal_Result>("buscar_personal", dniParameter, cargoParameter);
        }
    
        public virtual ObjectResult<buscar_promo_cod_Result> buscar_promo_cod(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_promo_cod_Result>("buscar_promo_cod", codParameter);
        }
    
        public virtual ObjectResult<buscar_promocion_Result> buscar_promocion(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_promocion_Result>("buscar_promocion", nombreParameter);
        }
    
        public virtual ObjectResult<Buscar_proveedor_Result> Buscar_proveedor(string codprov)
        {
            var codprovParameter = codprov != null ?
                new ObjectParameter("codprov", codprov) :
                new ObjectParameter("codprov", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Buscar_proveedor_Result>("Buscar_proveedor", codprovParameter);
        }
    
        public virtual ObjectResult<Buscar_proveedor2_Result> Buscar_proveedor2(string nomprov)
        {
            var nomprovParameter = nomprov != null ?
                new ObjectParameter("nomprov", nomprov) :
                new ObjectParameter("nomprov", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Buscar_proveedor2_Result>("Buscar_proveedor2", nomprovParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> buscar_puntos_clientes(string cod_cli)
        {
            var cod_cliParameter = cod_cli != null ?
                new ObjectParameter("cod_cli", cod_cli) :
                new ObjectParameter("cod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("buscar_puntos_clientes", cod_cliParameter);
        }
    
        public virtual ObjectResult<buscar_reserva_Result> buscar_reserva(Nullable<System.DateTime> fecha, string dni)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_reserva_Result>("buscar_reserva", fechaParameter, dniParameter);
        }
    
        public virtual ObjectResult<buscar_reserva2_Result> buscar_reserva2(string codre)
        {
            var codreParameter = codre != null ?
                new ObjectParameter("codre", codre) :
                new ObjectParameter("codre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_reserva2_Result>("buscar_reserva2", codreParameter);
        }
    
        public virtual ObjectResult<buscar_user_Result> buscar_user(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_user_Result>("buscar_user", dniParameter);
        }
    
        public virtual ObjectResult<buscar_user2_Result> buscar_user2(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscar_user2_Result>("buscar_user2", dniParameter);
        }
    
        public virtual int cambiar_estado_empleado(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cambiar_estado_empleado", codParameter);
        }
    
        public virtual int canjear_cupon(Nullable<int> codcupon)
        {
            var codcuponParameter = codcupon.HasValue ?
                new ObjectParameter("codcupon", codcupon) :
                new ObjectParameter("codcupon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("canjear_cupon", codcuponParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> contar_acceso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("contar_acceso");
        }
    
        public virtual ObjectResult<contar_dely_total_Result> contar_dely_total()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<contar_dely_total_Result>("contar_dely_total");
        }
    
        public virtual int desactiva_orden_por_proforma(Nullable<int> codorden)
        {
            var codordenParameter = codorden.HasValue ?
                new ObjectParameter("codorden", codorden) :
                new ObjectParameter("codorden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("desactiva_orden_por_proforma", codordenParameter);
        }
    
        public virtual int desactivar_orden(Nullable<int> codorden)
        {
            var codordenParameter = codorden.HasValue ?
                new ObjectParameter("codorden", codorden) :
                new ObjectParameter("codorden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("desactivar_orden", codordenParameter);
        }
    
        public virtual int desactivar_orden_delivery(Nullable<int> coddely)
        {
            var coddelyParameter = coddely.HasValue ?
                new ObjectParameter("coddely", coddely) :
                new ObjectParameter("coddely", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("desactivar_orden_delivery", coddelyParameter);
        }
    
        public virtual int descontar_puntos(string codcli, Nullable<int> cantidad)
        {
            var codcliParameter = codcli != null ?
                new ObjectParameter("codcli", codcli) :
                new ObjectParameter("codcli", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("descontar_puntos", codcliParameter, cantidadParameter);
        }
    
        public virtual int despacho_dely(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("despacho_dely", codParameter);
        }
    
        public virtual int eliminar_promocion(Nullable<int> cod_promo)
        {
            var cod_promoParameter = cod_promo.HasValue ?
                new ObjectParameter("cod_promo", cod_promo) :
                new ObjectParameter("cod_promo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminar_promocion", cod_promoParameter);
        }
    
        public virtual int estado_dely_recivido(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("estado_dely_recivido", codParameter);
        }
    
        public virtual int estado_despachado_orden(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("estado_despachado_orden", codParameter);
        }
    
        public virtual int estado_orden_recivido(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("estado_orden_recivido", codParameter);
        }
    
        public virtual int insertar_asistencia(string dni, Nullable<System.DateTime> fechaasis, Nullable<System.TimeSpan> horaasis)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var fechaasisParameter = fechaasis.HasValue ?
                new ObjectParameter("fechaasis", fechaasis) :
                new ObjectParameter("fechaasis", typeof(System.DateTime));
    
            var horaasisParameter = horaasis.HasValue ?
                new ObjectParameter("horaasis", horaasis) :
                new ObjectParameter("horaasis", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_asistencia", dniParameter, fechaasisParameter, horaasisParameter);
        }
    
        public virtual int insertar_cargo(string cod, string nombre, string descripcion)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_cargo", codParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int insertar_cat_plato(Nullable<int> codigo, string nombre, string descrip)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_cat_plato", codigoParameter, nombreParameter, descripParameter);
        }
    
        public virtual int insertar_cliente(string cod, string nombre, string apellido, string imagen, string telefono, string direccion, string distrito, string dni, string observacion, string tipocliente, Nullable<int> cod_usu_cliente)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var tipoclienteParameter = tipocliente != null ?
                new ObjectParameter("tipocliente", tipocliente) :
                new ObjectParameter("tipocliente", typeof(string));
    
            var cod_usu_clienteParameter = cod_usu_cliente.HasValue ?
                new ObjectParameter("cod_usu_cliente", cod_usu_cliente) :
                new ObjectParameter("cod_usu_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_cliente", codParameter, nombreParameter, apellidoParameter, imagenParameter, telefonoParameter, direccionParameter, distritoParameter, dniParameter, observacionParameter, tipoclienteParameter, cod_usu_clienteParameter);
        }
    
        public virtual int insertar_comprobante_pago(string codigo, Nullable<System.DateTime> fecha, string codtipo, Nullable<decimal> total, string codigocliente, string dni, string codper, Nullable<int> cod_cupon, Nullable<decimal> descuento)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var codtipoParameter = codtipo != null ?
                new ObjectParameter("codtipo", codtipo) :
                new ObjectParameter("codtipo", typeof(string));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var codigoclienteParameter = codigocliente != null ?
                new ObjectParameter("codigocliente", codigocliente) :
                new ObjectParameter("codigocliente", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            var cod_cuponParameter = cod_cupon.HasValue ?
                new ObjectParameter("cod_cupon", cod_cupon) :
                new ObjectParameter("cod_cupon", typeof(int));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("descuento", descuento) :
                new ObjectParameter("descuento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_comprobante_pago", codigoParameter, fechaParameter, codtipoParameter, totalParameter, codigoclienteParameter, dniParameter, codperParameter, cod_cuponParameter, descuentoParameter);
        }
    
        public virtual int insertar_delivery_cabe(Nullable<int> cod, string codcli, Nullable<System.DateTime> fecha, string codper, string estado, string coddis, string direccion)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var codcliParameter = codcli != null ?
                new ObjectParameter("codcli", codcli) :
                new ObjectParameter("codcli", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var coddisParameter = coddis != null ?
                new ObjectParameter("coddis", coddis) :
                new ObjectParameter("coddis", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_delivery_cabe", codParameter, codcliParameter, fechaParameter, codperParameter, estadoParameter, coddisParameter, direccionParameter);
        }
    
        public virtual int insertar_delivery_deta(Nullable<int> coddeli, string codmenu, Nullable<int> cantidad, Nullable<decimal> precio, Nullable<decimal> total)
        {
            var coddeliParameter = coddeli.HasValue ?
                new ObjectParameter("coddeli", coddeli) :
                new ObjectParameter("coddeli", typeof(int));
    
            var codmenuParameter = codmenu != null ?
                new ObjectParameter("codmenu", codmenu) :
                new ObjectParameter("codmenu", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_delivery_deta", coddeliParameter, codmenuParameter, cantidadParameter, precioParameter, totalParameter);
        }
    
        public virtual int insertar_detalle_boleta(string codpago, string codmenu, Nullable<int> cantidad, Nullable<decimal> total, Nullable<decimal> precio)
        {
            var codpagoParameter = codpago != null ?
                new ObjectParameter("codpago", codpago) :
                new ObjectParameter("codpago", typeof(string));
    
            var codmenuParameter = codmenu != null ?
                new ObjectParameter("codmenu", codmenu) :
                new ObjectParameter("codmenu", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_detalle_boleta", codpagoParameter, codmenuParameter, cantidadParameter, totalParameter, precioParameter);
        }
    
        public virtual int insertar_DetalleEntradaInsumo(Nullable<int> codentrada, string codinsumo, Nullable<int> cantidad, Nullable<decimal> precio, Nullable<decimal> subtotal)
        {
            var codentradaParameter = codentrada.HasValue ?
                new ObjectParameter("codentrada", codentrada) :
                new ObjectParameter("codentrada", typeof(int));
    
            var codinsumoParameter = codinsumo != null ?
                new ObjectParameter("codinsumo", codinsumo) :
                new ObjectParameter("codinsumo", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("subtotal", subtotal) :
                new ObjectParameter("subtotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_DetalleEntradaInsumo", codentradaParameter, codinsumoParameter, cantidadParameter, precioParameter, subtotalParameter);
        }
    
        public virtual int insertar_EntradaInsumo(string codpersonal, string codprove, Nullable<System.DateTime> fechaentrada, string numfactura, Nullable<decimal> precio_total)
        {
            var codpersonalParameter = codpersonal != null ?
                new ObjectParameter("codpersonal", codpersonal) :
                new ObjectParameter("codpersonal", typeof(string));
    
            var codproveParameter = codprove != null ?
                new ObjectParameter("codprove", codprove) :
                new ObjectParameter("codprove", typeof(string));
    
            var fechaentradaParameter = fechaentrada.HasValue ?
                new ObjectParameter("fechaentrada", fechaentrada) :
                new ObjectParameter("fechaentrada", typeof(System.DateTime));
    
            var numfacturaParameter = numfactura != null ?
                new ObjectParameter("numfactura", numfactura) :
                new ObjectParameter("numfactura", typeof(string));
    
            var precio_totalParameter = precio_total.HasValue ?
                new ObjectParameter("precio_total", precio_total) :
                new ObjectParameter("precio_total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_EntradaInsumo", codpersonalParameter, codproveParameter, fechaentradaParameter, numfacturaParameter, precio_totalParameter);
        }
    
        public virtual int insertar_factura_cabe(string cod, string cli, string ruc, string codtipo, string codper, Nullable<System.DateTime> fecha, Nullable<decimal> igv, Nullable<decimal> total, Nullable<int> cod_cupon, Nullable<decimal> descuento)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var cliParameter = cli != null ?
                new ObjectParameter("cli", cli) :
                new ObjectParameter("cli", typeof(string));
    
            var rucParameter = ruc != null ?
                new ObjectParameter("ruc", ruc) :
                new ObjectParameter("ruc", typeof(string));
    
            var codtipoParameter = codtipo != null ?
                new ObjectParameter("codtipo", codtipo) :
                new ObjectParameter("codtipo", typeof(string));
    
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var igvParameter = igv.HasValue ?
                new ObjectParameter("igv", igv) :
                new ObjectParameter("igv", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var cod_cuponParameter = cod_cupon.HasValue ?
                new ObjectParameter("cod_cupon", cod_cupon) :
                new ObjectParameter("cod_cupon", typeof(int));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("descuento", descuento) :
                new ObjectParameter("descuento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_factura_cabe", codParameter, cliParameter, rucParameter, codtipoParameter, codperParameter, fechaParameter, igvParameter, totalParameter, cod_cuponParameter, descuentoParameter);
        }
    
        public virtual int insertar_factura_deta(string codfact, string codmenu, Nullable<int> cantidad, Nullable<decimal> total, Nullable<decimal> prec_unit)
        {
            var codfactParameter = codfact != null ?
                new ObjectParameter("codfact", codfact) :
                new ObjectParameter("codfact", typeof(string));
    
            var codmenuParameter = codmenu != null ?
                new ObjectParameter("codmenu", codmenu) :
                new ObjectParameter("codmenu", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var prec_unitParameter = prec_unit.HasValue ?
                new ObjectParameter("prec_unit", prec_unit) :
                new ObjectParameter("prec_unit", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_factura_deta", codfactParameter, codmenuParameter, cantidadParameter, totalParameter, prec_unitParameter);
        }
    
        public virtual int insertar_Insumo(string codinsu, string nominsu, Nullable<int> cod_unidad_medida, Nullable<decimal> peso, string codcat)
        {
            var codinsuParameter = codinsu != null ?
                new ObjectParameter("codinsu", codinsu) :
                new ObjectParameter("codinsu", typeof(string));
    
            var nominsuParameter = nominsu != null ?
                new ObjectParameter("nominsu", nominsu) :
                new ObjectParameter("nominsu", typeof(string));
    
            var cod_unidad_medidaParameter = cod_unidad_medida.HasValue ?
                new ObjectParameter("cod_unidad_medida", cod_unidad_medida) :
                new ObjectParameter("cod_unidad_medida", typeof(int));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(decimal));
    
            var codcatParameter = codcat != null ?
                new ObjectParameter("codcat", codcat) :
                new ObjectParameter("codcat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Insumo", codinsuParameter, nominsuParameter, cod_unidad_medidaParameter, pesoParameter, codcatParameter);
        }
    
        public virtual int insertar_menu(string codigo, Nullable<int> catplato, string nomplato, Nullable<decimal> precio, string estado, string imagen, Nullable<System.DateTime> fecha, Nullable<int> cantidad, string descrip)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var catplatoParameter = catplato.HasValue ?
                new ObjectParameter("catplato", catplato) :
                new ObjectParameter("catplato", typeof(int));
    
            var nomplatoParameter = nomplato != null ?
                new ObjectParameter("nomplato", nomplato) :
                new ObjectParameter("nomplato", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_menu", codigoParameter, catplatoParameter, nomplatoParameter, precioParameter, estadoParameter, imagenParameter, fechaParameter, cantidadParameter, descripParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> insertar_orden_cabe(string codpersonal, string estado, Nullable<int> cod_mesa, Nullable<System.DateTime> fecha_orden)
        {
            var codpersonalParameter = codpersonal != null ?
                new ObjectParameter("codpersonal", codpersonal) :
                new ObjectParameter("codpersonal", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var cod_mesaParameter = cod_mesa.HasValue ?
                new ObjectParameter("cod_mesa", cod_mesa) :
                new ObjectParameter("cod_mesa", typeof(int));
    
            var fecha_ordenParameter = fecha_orden.HasValue ?
                new ObjectParameter("fecha_orden", fecha_orden) :
                new ObjectParameter("fecha_orden", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("insertar_orden_cabe", codpersonalParameter, estadoParameter, cod_mesaParameter, fecha_ordenParameter);
        }
    
        public virtual int insertar_orden_detalle(Nullable<int> cantidad, string codmenu, Nullable<int> cod_orden, Nullable<decimal> precio, Nullable<decimal> subtotal)
        {
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var codmenuParameter = codmenu != null ?
                new ObjectParameter("codmenu", codmenu) :
                new ObjectParameter("codmenu", typeof(string));
    
            var cod_ordenParameter = cod_orden.HasValue ?
                new ObjectParameter("cod_orden", cod_orden) :
                new ObjectParameter("cod_orden", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("subtotal", subtotal) :
                new ObjectParameter("subtotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_orden_detalle", cantidadParameter, codmenuParameter, cod_ordenParameter, precioParameter, subtotalParameter);
        }
    
        public virtual int insertar_personal(string codper, string codcargo, string nombre, string dni, string direccion, string telefono, string genero, string apellido, Nullable<System.DateTime> fechanacimiento, Nullable<System.DateTime> fechacontratacion, string coddistrito, string turno, string estado, Nullable<System.DateTime> fechafincontrato, byte[] foto)
        {
            var codperParameter = codper != null ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(string));
    
            var codcargoParameter = codcargo != null ?
                new ObjectParameter("codcargo", codcargo) :
                new ObjectParameter("codcargo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var fechanacimientoParameter = fechanacimiento.HasValue ?
                new ObjectParameter("fechanacimiento", fechanacimiento) :
                new ObjectParameter("fechanacimiento", typeof(System.DateTime));
    
            var fechacontratacionParameter = fechacontratacion.HasValue ?
                new ObjectParameter("fechacontratacion", fechacontratacion) :
                new ObjectParameter("fechacontratacion", typeof(System.DateTime));
    
            var coddistritoParameter = coddistrito != null ?
                new ObjectParameter("coddistrito", coddistrito) :
                new ObjectParameter("coddistrito", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechafincontratoParameter = fechafincontrato.HasValue ?
                new ObjectParameter("fechafincontrato", fechafincontrato) :
                new ObjectParameter("fechafincontrato", typeof(System.DateTime));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_personal", codperParameter, codcargoParameter, nombreParameter, dniParameter, direccionParameter, telefonoParameter, generoParameter, apellidoParameter, fechanacimientoParameter, fechacontratacionParameter, coddistritoParameter, turnoParameter, estadoParameter, fechafincontratoParameter, fotoParameter);
        }
    
        public virtual int insertar_promocion(string nombre_promocion, string descripcion_promocion, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin, Nullable<int> stock_promo, Nullable<int> puntos_necesarios, Nullable<decimal> valor_descuento, Nullable<bool> estado_promo, Nullable<int> cod_tipo_descuento)
        {
            var nombre_promocionParameter = nombre_promocion != null ?
                new ObjectParameter("nombre_promocion", nombre_promocion) :
                new ObjectParameter("nombre_promocion", typeof(string));
    
            var descripcion_promocionParameter = descripcion_promocion != null ?
                new ObjectParameter("descripcion_promocion", descripcion_promocion) :
                new ObjectParameter("descripcion_promocion", typeof(string));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            var stock_promoParameter = stock_promo.HasValue ?
                new ObjectParameter("stock_promo", stock_promo) :
                new ObjectParameter("stock_promo", typeof(int));
    
            var puntos_necesariosParameter = puntos_necesarios.HasValue ?
                new ObjectParameter("puntos_necesarios", puntos_necesarios) :
                new ObjectParameter("puntos_necesarios", typeof(int));
    
            var valor_descuentoParameter = valor_descuento.HasValue ?
                new ObjectParameter("valor_descuento", valor_descuento) :
                new ObjectParameter("valor_descuento", typeof(decimal));
    
            var estado_promoParameter = estado_promo.HasValue ?
                new ObjectParameter("estado_promo", estado_promo) :
                new ObjectParameter("estado_promo", typeof(bool));
    
            var cod_tipo_descuentoParameter = cod_tipo_descuento.HasValue ?
                new ObjectParameter("cod_tipo_descuento", cod_tipo_descuento) :
                new ObjectParameter("cod_tipo_descuento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_promocion", nombre_promocionParameter, descripcion_promocionParameter, fecha_inicioParameter, fecha_finParameter, stock_promoParameter, puntos_necesariosParameter, valor_descuentoParameter, estado_promoParameter, cod_tipo_descuentoParameter);
        }
    
        public virtual int insertar_proveedor(string codprov, string nomprov, string direc, string nomcont, string cargcont, string telfprov, string faxprov, string coddist, string ruc)
        {
            var codprovParameter = codprov != null ?
                new ObjectParameter("codprov", codprov) :
                new ObjectParameter("codprov", typeof(string));
    
            var nomprovParameter = nomprov != null ?
                new ObjectParameter("nomprov", nomprov) :
                new ObjectParameter("nomprov", typeof(string));
    
            var direcParameter = direc != null ?
                new ObjectParameter("direc", direc) :
                new ObjectParameter("direc", typeof(string));
    
            var nomcontParameter = nomcont != null ?
                new ObjectParameter("nomcont", nomcont) :
                new ObjectParameter("nomcont", typeof(string));
    
            var cargcontParameter = cargcont != null ?
                new ObjectParameter("cargcont", cargcont) :
                new ObjectParameter("cargcont", typeof(string));
    
            var telfprovParameter = telfprov != null ?
                new ObjectParameter("telfprov", telfprov) :
                new ObjectParameter("telfprov", typeof(string));
    
            var faxprovParameter = faxprov != null ?
                new ObjectParameter("faxprov", faxprov) :
                new ObjectParameter("faxprov", typeof(string));
    
            var coddistParameter = coddist != null ?
                new ObjectParameter("coddist", coddist) :
                new ObjectParameter("coddist", typeof(string));
    
            var rucParameter = ruc != null ?
                new ObjectParameter("ruc", ruc) :
                new ObjectParameter("ruc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_proveedor", codprovParameter, nomprovParameter, direcParameter, nomcontParameter, cargcontParameter, telfprovParameter, faxprovParameter, coddistParameter, rucParameter);
        }
    
        public virtual int insertar_reserva(string cod, Nullable<System.DateTime> fechareservada, string cliente, string estado, Nullable<int> codmesa, Nullable<System.TimeSpan> hora)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var fechareservadaParameter = fechareservada.HasValue ?
                new ObjectParameter("fechareservada", fechareservada) :
                new ObjectParameter("fechareservada", typeof(System.DateTime));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var codmesaParameter = codmesa.HasValue ?
                new ObjectParameter("codmesa", codmesa) :
                new ObjectParameter("codmesa", typeof(int));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_reserva", codParameter, fechareservadaParameter, clienteParameter, estadoParameter, codmesaParameter, horaParameter);
        }
    
        public virtual int insertar_SalidaInsumo(string codpersonal, Nullable<System.DateTime> fechasalida)
        {
            var codpersonalParameter = codpersonal != null ?
                new ObjectParameter("codpersonal", codpersonal) :
                new ObjectParameter("codpersonal", typeof(string));
    
            var fechasalidaParameter = fechasalida.HasValue ?
                new ObjectParameter("fechasalida", fechasalida) :
                new ObjectParameter("fechasalida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_SalidaInsumo", codpersonalParameter, fechasalidaParameter);
        }
    
        public virtual int insertar_SalidaInsumoDetalle(Nullable<int> codsalida, string codinsumos, Nullable<decimal> cantidad)
        {
            var codsalidaParameter = codsalida.HasValue ?
                new ObjectParameter("codsalida", codsalida) :
                new ObjectParameter("codsalida", typeof(int));
    
            var codinsumosParameter = codinsumos != null ?
                new ObjectParameter("codinsumos", codinsumos) :
                new ObjectParameter("codinsumos", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_SalidaInsumoDetalle", codsalidaParameter, codinsumosParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> insertar_sistema(Nullable<System.DateTime> fechaacceso, string ip, string coduser, string estado)
        {
            var fechaaccesoParameter = fechaacceso.HasValue ?
                new ObjectParameter("fechaacceso", fechaacceso) :
                new ObjectParameter("fechaacceso", typeof(System.DateTime));
    
            var ipParameter = ip != null ?
                new ObjectParameter("ip", ip) :
                new ObjectParameter("ip", typeof(string));
    
            var coduserParameter = coduser != null ?
                new ObjectParameter("coduser", coduser) :
                new ObjectParameter("coduser", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("insertar_sistema", fechaaccesoParameter, ipParameter, coduserParameter, estadoParameter);
        }
    
        public virtual ObjectResult<listar_asistencia_Result> listar_asistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_asistencia_Result>("listar_asistencia");
        }
    
        public virtual ObjectResult<listar_cargo_Result> listar_cargo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_cargo_Result>("listar_cargo");
        }
    
        public virtual ObjectResult<listar_cat_plato_Result> listar_cat_plato()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_cat_plato_Result>("listar_cat_plato");
        }
    
        public virtual ObjectResult<Listar_Catid_Result> Listar_Catid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_Catid_Result>("Listar_Catid");
        }
    
        public virtual ObjectResult<listar_clientes_Result> listar_clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_clientes_Result>("listar_clientes");
        }
    
        public virtual ObjectResult<listar_clientes_tipo_Result> listar_clientes_tipo(string tipocli)
        {
            var tipocliParameter = tipocli != null ?
                new ObjectParameter("tipocli", tipocli) :
                new ObjectParameter("tipocli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_clientes_tipo_Result>("listar_clientes_tipo", tipocliParameter);
        }
    
        public virtual ObjectResult<listar_comprobantes_Result> listar_comprobantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_comprobantes_Result>("listar_comprobantes");
        }
    
        public virtual ObjectResult<Nullable<int>> listar_deliverys_sin_pagar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("listar_deliverys_sin_pagar");
        }
    
        public virtual ObjectResult<listar_dely_Result> listar_dely()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_dely_Result>("listar_dely");
        }
    
        public virtual ObjectResult<listar_dely_deta_Result> listar_dely_deta(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_dely_deta_Result>("listar_dely_deta", codParameter);
        }
    
        public virtual ObjectResult<listar_detalle_delivery_Result> listar_detalle_delivery(Nullable<int> coddely)
        {
            var coddelyParameter = coddely.HasValue ?
                new ObjectParameter("coddely", coddely) :
                new ObjectParameter("coddely", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_detalle_delivery_Result>("listar_detalle_delivery", coddelyParameter);
        }
    
        public virtual ObjectResult<listar_distrito_Result> listar_distrito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_distrito_Result>("listar_distrito");
        }
    
        public virtual ObjectResult<Listar_insumo_Result> Listar_insumo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_insumo_Result>("Listar_insumo");
        }
    
        public virtual ObjectResult<listar_ip_Result> listar_ip()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_ip_Result>("listar_ip");
        }
    
        public virtual ObjectResult<listar_menu_Result> listar_menu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_menu_Result>("listar_menu");
        }
    
        public virtual ObjectResult<listar_mesas_Result> listar_mesas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_mesas_Result>("listar_mesas");
        }
    
        public virtual ObjectResult<listar_mesas_reservadas_Result> listar_mesas_reservadas(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_mesas_reservadas_Result>("listar_mesas_reservadas", fechaParameter);
        }
    
        public virtual ObjectResult<listar_mesas_sin_reserva_Result> listar_mesas_sin_reserva(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_mesas_sin_reserva_Result>("listar_mesas_sin_reserva", fechaParameter);
        }
    
        public virtual ObjectResult<listar_orden_detalle_Result> listar_orden_detalle(Nullable<int> mesa)
        {
            var mesaParameter = mesa.HasValue ?
                new ObjectParameter("mesa", mesa) :
                new ObjectParameter("mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_orden_detalle_Result>("listar_orden_detalle", mesaParameter);
        }
    
        public virtual ObjectResult<listar_ordenes_Result> listar_ordenes(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_ordenes_Result>("listar_ordenes", codParameter);
        }
    
        public virtual ObjectResult<listar_ordenes_sin_pagar_Result> listar_ordenes_sin_pagar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_ordenes_sin_pagar_Result>("listar_ordenes_sin_pagar");
        }
    
        public virtual ObjectResult<listar_ordenes_sin_pagar_caja_Result> listar_ordenes_sin_pagar_caja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_ordenes_sin_pagar_caja_Result>("listar_ordenes_sin_pagar_caja");
        }
    
        public virtual ObjectResult<listar_ordens_cabe_Result> listar_ordens_cabe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_ordens_cabe_Result>("listar_ordens_cabe");
        }
    
        public virtual ObjectResult<listar_personal_Result> listar_personal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_personal_Result>("listar_personal");
        }
    
        public virtual ObjectResult<listar_personal_turno_Result> listar_personal_turno(string turno)
        {
            var turnoParameter = turno != null ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_personal_turno_Result>("listar_personal_turno", turnoParameter);
        }
    
        public virtual ObjectResult<listar_promociones_Result> listar_promociones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_promociones_Result>("listar_promociones");
        }
    
        public virtual ObjectResult<listar_promociones_imprimir_Result> listar_promociones_imprimir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_promociones_imprimir_Result>("listar_promociones_imprimir");
        }
    
        public virtual ObjectResult<Listar_proveedor_Result> Listar_proveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_proveedor_Result>("Listar_proveedor");
        }
    
        public virtual ObjectResult<listar_reservacion_Result> listar_reservacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_reservacion_Result>("listar_reservacion");
        }
    
        public virtual ObjectResult<listar_tipo_descuento_Result> listar_tipo_descuento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_tipo_descuento_Result>("listar_tipo_descuento");
        }
    
        public virtual ObjectResult<listar_unidad_medida_Result> listar_unidad_medida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_unidad_medida_Result>("listar_unidad_medida");
        }
    
        public virtual ObjectResult<listar_usuarios_Result> listar_usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_usuarios_Result>("listar_usuarios");
        }
    
        public virtual ObjectResult<string> max_boleta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("max_boleta");
        }
    
        public virtual ObjectResult<Nullable<int>> max_cabe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("max_cabe");
        }
    
        public virtual ObjectResult<string> max_codigo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("max_codigo");
        }
    
        public virtual ObjectResult<string> max_codigo_Cli()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("max_codigo_Cli");
        }
    
        public virtual ObjectResult<Nullable<int>> max_codigo_entrada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("max_codigo_entrada");
        }
    
        public virtual ObjectResult<string> max_factura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("max_factura");
        }
    
        public virtual ObjectResult<string> Max_insumo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Max_insumo");
        }
    
        public virtual ObjectResult<Nullable<int>> max_promo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("max_promo");
        }
    
        public virtual ObjectResult<string> max_provedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("max_provedor");
        }
    
        public virtual ObjectResult<string> max_reservacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("max_reservacion");
        }
    
        public virtual ObjectResult<Nullable<int>> max_salida_insumo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("max_salida_insumo");
        }
    
        public virtual ObjectResult<string> maxcargo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maxcargo");
        }
    
        public virtual ObjectResult<Nullable<int>> maxcodigocat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("maxcodigocat");
        }
    
        public virtual ObjectResult<string> maxcodigoplato()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maxcodigoplato");
        }
    
        public virtual int restar_menu(string cod, Nullable<int> cantida)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var cantidaParameter = cantida.HasValue ?
                new ObjectParameter("cantida", cantida) :
                new ObjectParameter("cantida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("restar_menu", codParameter, cantidaParameter);
        }
    
        public virtual ObjectResult<verificar_datos_Result> verificar_datos(string dni, string contrasena)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verificar_datos_Result>("verificar_datos", dniParameter, contrasenaParameter);
        }
    
        public virtual int registrarUsuarioClienteNuevo(string usuario, string pass, string email, string token, ObjectParameter id)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("registrarUsuarioClienteNuevo", usuarioParameter, passParameter, emailParameter, tokenParameter, id);
        }
    }
}
